version: "3"

services:
  app:
    container_name: voltr_app
    image: emadou/voltr-app:0.1
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./api/uploaded/imgs:/app/api/uploaded/imgs
  database:
    container_name: voltr_db
    image: emadou/voltr-db:0.1
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: root
      MARIADB_DATABASE: voltr
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - voltr_db:/var/lib/mysql
  php:
    container_name: voltr_phpcgi
    image: emadou/voltr-phpcgi:0.1
    volumes:
      - ./api/uploaded/imgs:/app/api/uploaded/imgs
    expose:
      - 9000

volumes:
  voltr_db:
