version: "3"
services:
  server:
    container_name: server
    build: ./nginx
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  database:
    image: mariadb:10.9
    container_name: database
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: root
      MARIADB_DATABASE: voltr
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./api/db:/var/lib/mysql
      - ./api/database.sql:/docker-entrypoint-initdb.d/database.sql
  php:
    build:
      context: ./api
    container_name: phpcgi
    volumes:
      - .:/app
    expose:
      - 9000
