version: "3"
services:
  server:
    container_name: server
    build: .
    ports:
      - 80:80
    links:
      - php
  database:
    image: voltr/database
    build:
      context: .
      dockerfile: ./db.Dockerfile
    container_name: database
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: root
      MARIADB_DATABASE: voltr
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - source: voltr_db
        target: /var/lib/mysql
        type: volume
        volume:
          nocopy: true
  php:
    build:
      context: ./api
    container_name: phpcgi
    expose:
      - 9000
volumes:
  voltr_db:
